# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 984874e4938078d1ffaf02794e8f6bb60ec4de7d86de045aed1d42f3bc26403024b97f8c24842ed577e8f8a0bb5e04d38ce2b7feecc5de1c2f973d2cfd137fae

test:
  secret_key_base: 83bdc758694c36309d92184e259ab50173ca5922629bc1867538eac34c713d5aa761b05dc6fc106dba656fb2ac02cee88c928e7b714c7461ecdf130719c1ae0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
